import { Data } from "../../code-challenge/types";

export const mockData: Data[] = [
  {
    country: "USA",
    state: "California",
    city: "Los Angelas",
    person: "Mr. Tara Beier",
  },
  {
    country: "USA",
    state: "California",
    city: "Los Angelas",
    person: "Dianne Keebler",
  },
  {
    country: "USA",
    state: "California",
    city: "Los Angelas",
    person: "Frankie Krajcik",
  },
  {
    country: "USA",
    state: "California",
    city: "Los Angelas",
    person: "Jeannette Skiles",
  },
  {
    country: "USA",
    state: "California",
    city: "Los Angelas",
    person: "Shirley Bahringer",
  },
  {
    country: "USA",
    state: "California",
    city: "Los Angelas",
    person: "Dave Wilkinson",
  },
  {
    country: "USA",
    state: "California",
    city: "San Francisco",
    person: "Andy Zulauf",
  },
  {
    country: "USA",
    state: "California",
    city: "San Francisco",
    person: "Esther Strosin",
  },
  {
    country: "USA",
    state: "California",
    city: "San Francisco",
    person: "Jacqueline Gislason",
  },
  {
    country: "USA",
    state: "California",
    city: "San Francisco",
    person: "Mrs. Stephen Sawayn",
  },
  {
    country: "USA",
    state: "California",
    city: "San Jose",
    person: "Ms. Cora Mann",
  },
  {
    country: "USA",
    state: "California",
    city: "San Jose",
    person: "Ida Blick",
  },
  {
    country: "USA",
    state: "California",
    city: "San Jose",
    person: "Jeanne Cronin",
  },
  {
    country: "USA",
    state: "California",
    city: "San Jose",
    person: "Taylor Hackett",
  },
  {
    country: "USA",
    state: "California",
    city: "San Jose",
    person: "Regina Dach",
  },
  {
    country: "USA",
    state: "New York",
    city: "New York City",
    person: "Joseph Durgan",
  },
  {
    country: "USA",
    state: "New York",
    city: "New York City",
    person: "Rosalie Hintz",
  },
  {
    country: "USA",
    state: "New York",
    city: "New York City",
    person: "Mr. Edmund Rath",
  },
  {
    country: "USA",
    state: "New York",
    city: "New York City",
    person: "Lindsey Hamill",
  },
  {
    country: "USA",
    state: "New York",
    city: "New York City",
    person: "Peggy Murray",
  },
  {
    country: "USA",
    state: "New York",
    city: "Buffalo",
    person: "Karla McGlynn",
  },
  {
    country: "USA",
    state: "New York",
    city: "Buffalo",
    person: "Ken Mann",
  },
  {
    country: "USA",
    state: "New York",
    city: "Buffalo",
    person: "Leroy Turner",
  },
  {
    country: "USA",
    state: "New York",
    city: "Buffalo",
    person: "Sabrina Runolfsson",
  },
  {
    country: "USA",
    state: "New York",
    city: "Buffalo",
    person: "Gilbert Simonis",
  },
  {
    country: "USA",
    state: "New York",
    city: "Buffalo",
    person: "Garry Ondricka",
  },
  {
    country: "USA",
    state: "New York",
    city: "Rochester",
    person: "Margaret Konopelski",
  },
  {
    country: "USA",
    state: "New York",
    city: "Rochester",
    person: "Ms. Darryl Doyle",
  },
  {
    country: "USA",
    state: "New York",
    city: "Rochester",
    person: "Henry Douglas",
  },
  {
    country: "USA",
    state: "New York",
    city: "Rochester",
    person: "Monica Medhurst",
  },
  {
    country: "USA",
    state: "New York",
    city: "Niagara Falls",
    person: "Gerardo Homenick",
  },
  {
    country: "USA",
    state: "New York",
    city: "Niagara Falls",
    person: "Cathy Bartoletti",
  },
  {
    country: "USA",
    state: "New York",
    city: "Niagara Falls",
    person: "Karl Steuber",
  },
  {
    country: "USA",
    state: "New York",
    city: "Niagara Falls",
    person: "Max Emmerich",
  },
  {
    country: "USA",
    state: "New York",
    city: "Niagara Falls",
    person: "Ms. Maureen Tillman",
  },
  {
    country: "USA",
    state: "New York",
    city: "Niagara Falls",
    person: "Mr. Garry Baumbach",
  },
  {
    country: "USA",
    state: "New York",
    city: "Niagara Falls",
    person: "Jan Stehr",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Huston",
    person: "Dave Moore",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Huston",
    person: "Jennifer Quigley",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Huston",
    person: "Samantha Kihn III",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Huston",
    person: "Miss Lynette Renner I",
  },
  {
    country: "USA",
    state: "Texas",
    city: "San Antonio",
    person: "Lucille Greenfelder V",
  },
  {
    country: "USA",
    state: "Texas",
    city: "San Antonio",
    person: "Wilbur Hartmann Jr.",
  },
  {
    country: "USA",
    state: "Texas",
    city: "San Antonio",
    person: "Olga Konopelski Sr.",
  },
  {
    country: "USA",
    state: "Texas",
    city: "San Antonio",
    person: "Nicolas Weber",
  },
  {
    country: "USA",
    state: "Texas",
    city: "San Antonio",
    person: "Allen Tillman",
  },
  {
    country: "USA",
    state: "Texas",
    city: "San Antonio",
    person: "Manuel Wilkinson",
  },
  {
    country: "USA",
    state: "Texas",
    city: "San Antonio",
    person: "Debbie Kshlerin",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Dallas",
    person: "Genevieve Vandervort",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Dallas",
    person: "Dave Sawayn",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Dallas",
    person: "Kent O'Kon MD",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Dallas",
    person: "Mr. Eduardo Jenkins",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Dallas",
    person: "Arturo Stracke",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Austin",
    person: "Carlos Ankunding",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Austin",
    person: "Jay Leannon",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Austin",
    person: "Darlene Schmeler",
  },
  {
    country: "USA",
    state: "Texas",
    city: "Austin",
    person: "Neal McKenzie",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    person: "Shannon Bahringer",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    person: "Leo Shanahan",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    person: "Alison Oberbrunner",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    person: "Patrick Gislason I",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    person: "Gwen Ward",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    person: "Vanessa Hegmann PhD",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    person: "Jennifer Spencer",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Ottawa",
    person: "Leon Weimann",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Ottawa",
    person: "Patricia Prosacco",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Ottawa",
    person: "Amy Carroll",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Ottawa",
    person: "Shawn Hansen",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Hamilton",
    person: "Saul Spencer",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Hamilton",
    person: "Noel Collier",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Hamilton",
    person: "Leroy Hartmann",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Hamilton",
    person: "Betsy Zemlak",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Hamilton",
    person: "Shannon Jacobson",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Hamilton",
    person: "Julie Bayer",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "Hamilton",
    person: "Jesse Stroman",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "North Bay",
    person: "Jack Hills V",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "North Bay",
    person: "Edwin DuBuque",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "North Bay",
    person: "Andy Rolfson",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "North Bay",
    person: "Horace Hansen IV",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "North Bay",
    person: "Tiffany Haag",
  },
  {
    country: "Canada",
    state: "Ontario",
    city: "North Bay",
    person: "Lee Funk",
  },
  {
    country: "Canada",
    state: "British Columbia",
    city: "Vancouver",
    person: "Patsy Johnson III",
  },
  {
    country: "Canada",
    state: "British Columbia",
    city: "Vancouver",
    person: "Miss Cornelius Breitenberg",
  },
  {
    country: "Canada",
    state: "British Columbia",
    city: "Vancouver",
    person: "Mrs. Carlos Volkman V",
  },
  {
    country: "Canada",
    state: "British Columbia",
    city: "Vancouver",
    person: "Alexis Lang",
  },
  {
    country: "Canada",
    state: "British Columbia",
    city: "Victoria",
    person: "Della Stark",
  },
  {
    country: "Canada",
    state: "British Columbia",
    city: "Victoria",
    person: "Jaime Konopelski",
  },
  {
    country: "Canada",
    state: "British Columbia",
    city: "Victoria",
    person: "Leslie Swaniawski",
  },
  {
    country: "Canada",
    state: "British Columbia",
    city: "Victoria",
    person: "Orlando Howe",
  },
  {
    country: "Canada",
    state: "British Columbia",
    city: "Victoria",
    person: "Ricky Schuster",
  },
  {
    country: "Canada",
    state: "British Columbia",
    city: "Victoria",
    person: "Hattie Bailey",
  },
  {
    country: "Canada",
    state: "British Columbia",
    city: "Victoria",
    person: "Martin Marks",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Montreal",
    person: "Jonathon Mohr",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Montreal",
    person: "Shane Beatty",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Montreal",
    person: "Gladys Hickle DVM",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Montreal",
    person: "Jim Wunsch",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Quebec City",
    person: "Kayla Koelpin",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Quebec City",
    person: "Sally Gulgowski",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Quebec City",
    person: "Stephen Lang",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Quebec City",
    person: "Casey Bogisich",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Quebec City",
    person: "Leah Hermiston",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Quebec City",
    person: "Mrs. Freda Graham",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Laval",
    person: "Lynda Lockman IV",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Laval",
    person: "Jane Lind",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Laval",
    person: "Charlie Streich",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Laval",
    person: "Virginia Kunze Sr.",
  },
  {
    country: "Canada",
    state: "Quebec",
    city: "Laval",
    person: "Shelia Donnelly",
  },
  {
    country: "Australia",
    state: "Victoria",
    city: "Melbourne",
    person: "Kurt Connelly",
  },
  {
    country: "Australia",
    state: "Victoria",
    city: "Melbourne",
    person: "Mrs. Rufus Champlin",
  },
  {
    country: "Australia",
    state: "Victoria",
    city: "Melbourne",
    person: "Andrea Goyette",
  },
  {
    country: "Australia",
    state: "Victoria",
    city: "Melbourne",
    person: "Marshall Goldner",
  },
  {
    country: "Australia",
    state: "Victoria",
    city: "Melbourne",
    person: "Gilbert Corkery",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Sydney",
    person: "Lionel Herman",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Sydney",
    person: "Jana Koelpin",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Sydney",
    person: "Jonathon Nitzsche",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Sydney",
    person: "Aaron Kassulke",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Newcastle",
    person: "Leland Nikolaus",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Newcastle",
    person: "Brittany Kemmer",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Newcastle",
    person: "Dr. Eunice Bins",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Newcastle",
    person: "Kendra Watsica",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Newcastle",
    person: "Jaime Durgan",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Central Coast",
    person: "Alonzo Sauer",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Central Coast",
    person: "Caleb Torp",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Central Coast",
    person: "Mrs. Dexter Greenholt",
  },
  {
    country: "Australia",
    state: "New South Wales",
    city: "Central Coast",
    person: "Derrick Sanford",
  },
  {
    country: "Australia",
    state: "Queensland",
    city: "Brisbane",
    person: "Lucy Olson",
  },
  {
    country: "Australia",
    state: "Queensland",
    city: "Brisbane",
    person: "Johnnie Pacocha",
  },
  {
    country: "Australia",
    state: "Queensland",
    city: "Brisbane",
    person: "Herbert Hessel MD",
  },
  {
    country: "Australia",
    state: "Queensland",
    city: "Brisbane",
    person: "Darrell Hamill",
  },
  {
    country: "Australia",
    state: "Queensland",
    city: "Brisbane",
    person: "Wilbur Marks",
  },
  {
    country: "Australia",
    state: "Queensland",
    city: "Brisbane",
    person: "Stanley Rosenbaum",
  },
  {
    country: "Australia",
    state: "Queensland",
    city: "Brisbane",
    person: "Roderick Kris",
  },
  {
    country: "Australia",
    state: "Queensland",
    city: "Gold Coast",
    person: "Rosa Parisian DDS",
  },
  {
    country: "Australia",
    state: "Queensland",
    city: "Gold Coast",
    person: "Jean Harris",
  },
  {
    country: "Australia",
    state: "Queensland",
    city: "Gold Coast",
    person: "Brian Hudson",
  },
  {
    country: "Australia",
    state: "Queensland",
    city: "Gold Coast",
    person: "Forrest McDermott",
  },
  {
    country: "Australia",
    state: "Queensland",
    city: "Gold Coast",
    person: "Jack Mitchell",
  },
];
